# Generated by Django 4.0.1 on 2022-01-29 04:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_address_remove_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm3_en', models.CharField(max_length=50)),
                ('adm3_pcode', models.CharField(max_length=50)),
                ('adm4_en', models.CharField(max_length=50)),
                ('adm4_pcode', models.CharField(max_length=50)),
                ('adm4_ref', models.CharField(max_length=50)),
                ('adm4alt1en', models.CharField(max_length=50)),
                ('adm4alt2en', models.CharField(max_length=50)),
                ('point_x', models.FloatField()),
                ('point_y', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
