# Generated by Django 4.0.1 on 2022-01-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_area_adm0_en_alter_area_adm0_pcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='District',
        ),
    ]
