# Generated by Django 4.0.1 on 2022-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_country_fips_alter_country_iso2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='fips',
            field=models.CharField(max_length=50),
        ),
    ]
