# Generated by Django 4.0.3 on 2022-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='total_worker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='total_worker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
