# Generated by Django 4.0.3 on 2022-03-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden_activity', '0002_floor_total_worker_line_total_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddenactivity',
            name='worker_uuid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
