# Generated by Django 4.0.3 on 2022-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden_activity', '0004_alter_forbiddenactivity_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddenactivity',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
