# Generated by Django 4.0.1 on 2022-01-21 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_todo_alter_categorie_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RemoveField(
            model_name='unites',
            name='logo',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='category_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productstocks',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
