# Generated by Django 4.0.1 on 2022-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_todo_remove_unites_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categorie',
            name='deescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='root_categories',
            field=models.ManyToManyField(blank=True, related_name='root_categories', to='products.Categorie'),
        ),
    ]
