# Generated by Django 4.0.1 on 2022-01-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_categorie_category_id_categorie_deescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='root_categories',
        ),
        migrations.AddField(
            model_name='categorie',
            name='root_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_categories', to='products.categorie'),
        ),
    ]
