# Generated by Django 4.0.1 on 2022-02-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_categorie_root_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='sub_categorie',
        ),
        migrations.AddField(
            model_name='categorie',
            name='sub_categorie',
            field=models.ManyToManyField(blank=True, to='products.Categorie'),
        ),
    ]
