# Generated by Django 4.0.1 on 2022-02-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_categorie_sub_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='sub_categorie',
        ),
        migrations.AddField(
            model_name='categorie',
            name='sub_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='products.categorie'),
        ),
    ]
