# Generated by Django 4.0.3 on 2022-03-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden_activity', '0003_forbiddenactivity_worker_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forbiddenactivity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forbiddenactivity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
