create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19, 2) NOT NULL
);
insert into car (make, model, price) values ('Mazda', 'RX-8', '12555.25');
insert into car (make, model, price) values ('Nissan', 'Titan', '60622.48');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '54100.95');
insert into car (make, model, price) values ('Saturn', 'Ion', '39914.72');
insert into car (make, model, price) values ('Porsche', '924 S', '98794.17');
insert into car (make, model, price) values ('GMC', '3500', '44376.30');
insert into car (make, model, price) values ('Land Rover', 'Defender', '31639.32');
insert into car (make, model, price) values ('Mercury', 'Sable', '95731.87');
insert into car (make, model, price) values ('Mazda', 'MX-6', '59094.19');
insert into car (make, model, price) values ('Subaru', 'XT', '63738.13');
insert into car (make, model, price) values ('Maybach', 'Landaulet', '90652.94');
insert into car (make, model, price) values ('Honda', 'Accord Crosstour', '48904.44');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '12163.57');
insert into car (make, model, price) values ('Mercury', 'Villager', '37099.84');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '23818.77');
insert into car (make, model, price) values ('Ford', 'Bronco', '38430.09');
insert into car (make, model, price) values ('Ford', 'Windstar', '93306.50');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '16896.20');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '43551.31');
insert into car (make, model, price) values ('Hummer', 'H2 SUT', '32231.28');
insert into car (make, model, price) values ('Ford', 'Festiva', '43241.77');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '71174.76');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '90159.88');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '82653.47');
insert into car (make, model, price) values ('Plymouth', 'Neon', '46869.99');
insert into car (make, model, price) values ('Volkswagen', 'Touareg', '82442.57');
insert into car (make, model, price) values ('Hyundai', 'Entourage', '40487.10');
insert into car (make, model, price) values ('Suzuki', 'Verona', '78134.94');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '42388.22');
insert into car (make, model, price) values ('Mazda', 'CX-7', '55441.69');
insert into car (make, model, price) values ('Mercury', 'Topaz', '65350.99');
insert into car (make, model, price) values ('Lexus', 'HS', '18801.92');
insert into car (make, model, price) values ('Porsche', '911', '48130.64');
insert into car (make, model, price) values ('Toyota', 'Prius', '12784.20');
insert into car (make, model, price) values ('GMC', 'Yukon', '46349.74');
insert into car (make, model, price) values ('Aptera', 'Type-1h', '20406.10');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '88704.22');
insert into car (make, model, price) values ('Audi', 'TT', '62516.39');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '36624.68');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '10223.47');
insert into car (make, model, price) values ('Mercury', 'Sable', '23517.89');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '12900.88');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '96052.53');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '81912.24');
insert into car (make, model, price) values ('Chrysler', 'Imperial', '91841.76');
insert into car (make, model, price) values ('Ford', 'Expedition', '83866.24');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '88834.53');
insert into car (make, model, price) values ('Mercury', 'Topaz', '31077.55');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '63763.92');
insert into car (make, model, price) values ('Honda', 'S2000', '24454.17');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '32671.22');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '45914.79');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '95573.94');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '72113.96');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt', '68568.12');
insert into car (make, model, price) values ('Mazda', 'MPV', '89761.20');
insert into car (make, model, price) values ('Chevrolet', 'Express', '53830.08');
insert into car (make, model, price) values ('BMW', '3 Series', '17802.00');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '99283.47');
insert into car (make, model, price) values ('Honda', 'Prelude', '39745.05');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '85419.69');
insert into car (make, model, price) values ('Acura', 'TL', '91078.17');
insert into car (make, model, price) values ('Ford', 'Ranger', '52492.86');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '81863.94');
insert into car (make, model, price) values ('GMC', 'Vandura 1500', '41383.38');
insert into car (make, model, price) values ('Mercury', 'Lynx', '88447.19');
insert into car (make, model, price) values ('Toyota', 'Tundra', '29497.20');
insert into car (make, model, price) values ('Volvo', 'XC90', '87157.64');
insert into car (make, model, price) values ('Lexus', 'LX', '59584.39');
insert into car (make, model, price) values ('Chevrolet', 'Classic', '92213.25');
insert into car (make, model, price) values ('Hyundai', 'Veracruz', '19148.81');
insert into car (make, model, price) values ('Cadillac', 'Seville', '59518.42');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '11095.24');
insert into car (make, model, price) values ('GMC', 'Safari', '81305.42');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '74006.50');
insert into car (make, model, price) values ('Saab', '900', '29387.82');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '59651.80');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '49120.94');
insert into car (make, model, price) values ('Toyota', 'Prius', '98805.00');
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', '29275.21');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '37428.83');
insert into car (make, model, price) values ('Geo', 'Tracker', '21459.65');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '81670.56');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '48888.46');
insert into car (make, model, price) values ('Nissan', '240SX', '18983.15');
insert into car (make, model, price) values ('Ford', 'Mustang', '99203.96');
insert into car (make, model, price) values ('GMC', 'Vandura G1500', '74976.86');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '26269.23');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '26813.45');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '94891.90');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '64930.10');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '20609.41');
insert into car (make, model, price) values ('Maserati', 'Karif', '97564.00');
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', '58560.28');
insert into car (make, model, price) values ('Mazda', '626', '89601.34');
insert into car (make, model, price) values ('Toyota', 'Previa', '26404.48');
insert into car (make, model, price) values ('Nissan', '370Z', '89240.73');
insert into car (make, model, price) values ('Buick', 'Riviera', '81418.17');
insert into car (make, model, price) values ('Nissan', 'Sentra', '23096.62');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '42028.66');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '31451.57');
insert into car (make, model, price) values ('Mercury', 'Mariner', '45198.57');
insert into car (make, model, price) values ('Dodge', 'Shadow', '88006.94');
insert into car (make, model, price) values ('Infiniti', 'M', '42143.29');
insert into car (make, model, price) values ('Maybach', '62', '21025.29');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '28769.13');
insert into car (make, model, price) values ('GMC', 'Yukon', '68050.79');
insert into car (make, model, price) values ('GMC', 'Envoy', '36481.02');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '95734.73');
insert into car (make, model, price) values ('Pontiac', 'G5', '36855.19');
insert into car (make, model, price) values ('GMC', 'Yukon', '24789.26');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '73200.46');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '52495.19');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '97658.11');
insert into car (make, model, price) values ('Saab', '900', '68517.35');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '53232.18');
insert into car (make, model, price) values ('GMC', 'Sonoma Club', '36711.88');
insert into car (make, model, price) values ('Lexus', 'IS', '62909.03');
insert into car (make, model, price) values ('Ford', 'ZX2', '91368.56');
insert into car (make, model, price) values ('Audi', 'S4', '17649.90');
insert into car (make, model, price) values ('Mitsubishi', 'GTO', '86005.27');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '94348.95');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '14129.39');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '88897.69');
insert into car (make, model, price) values ('Toyota', 'Highlander', '45231.09');
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', '67671.15');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '95940.52');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '63272.93');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '18661.90');
insert into car (make, model, price) values ('Audi', 'A4', '54857.26');
insert into car (make, model, price) values ('Chevrolet', 'Corvair', '15930.05');
insert into car (make, model, price) values ('Toyota', 'Avalon', '94279.71');
insert into car (make, model, price) values ('Ford', 'E-Series', '20974.31');
insert into car (make, model, price) values ('Audi', 'Quattro', '93078.31');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '43155.76');
insert into car (make, model, price) values ('Nissan', 'Maxima', '77660.62');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '33829.70');
insert into car (make, model, price) values ('Dodge', 'Monaco', '89448.53');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '23378.17');
insert into car (make, model, price) values ('Buick', 'Lucerne', '45770.42');
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', '70218.57');
insert into car (make, model, price) values ('Mazda', 'B2600', '49231.57');
insert into car (make, model, price) values ('Pontiac', 'G6', '19952.37');
insert into car (make, model, price) values ('Nissan', 'Maxima', '70994.73');
insert into car (make, model, price) values ('Kia', 'Forte', '35477.80');
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', '72513.41');
insert into car (make, model, price) values ('BMW', 'Z4', '74455.10');
insert into car (make, model, price) values ('Toyota', 'Avalon', '56423.71');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '73768.29');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '26499.96');
insert into car (make, model, price) values ('Aston Martin', 'Virage', '12938.15');
insert into car (make, model, price) values ('Nissan', 'Maxima', '26708.12');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '64184.94');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '89675.76');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '27803.63');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '12474.40');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '62139.62');
insert into car (make, model, price) values ('Acura', 'RL', '48553.85');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '41559.00');
insert into car (make, model, price) values ('Scion', 'tC', '32661.70');
insert into car (make, model, price) values ('Chevrolet', '3500', '99466.44');
insert into car (make, model, price) values ('Porsche', 'Panamera', '66438.37');
insert into car (make, model, price) values ('Kia', 'Rio', '32198.55');
insert into car (make, model, price) values ('Ford', 'F350', '68750.92');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '83700.21');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '71018.77');
insert into car (make, model, price) values ('Mitsubishi', 'L300', '82317.60');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '89033.38');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '92836.59');
insert into car (make, model, price) values ('Dodge', 'Dakota', '56755.72');
insert into car (make, model, price) values ('Kia', 'Sorento', '51766.93');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '96997.36');
insert into car (make, model, price) values ('Volkswagen', 'R32', '30062.57');
insert into car (make, model, price) values ('Audi', '80', '36913.04');
insert into car (make, model, price) values ('Ford', 'Windstar', '14458.37');
insert into car (make, model, price) values ('Pontiac', 'Montana', '53265.12');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '89347.75');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '59957.44');
insert into car (make, model, price) values ('Ford', 'F250', '86344.26');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '97958.19');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '73870.36');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '70340.28');
insert into car (make, model, price) values ('Infiniti', 'FX', '49791.17');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '40292.97');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '64298.00');
insert into car (make, model, price) values ('Ford', 'F250', '48663.40');
insert into car (make, model, price) values ('Mercury', 'Marquis', '74675.96');
insert into car (make, model, price) values ('Volvo', 'S40', '88203.64');
insert into car (make, model, price) values ('Ford', 'Focus', '38202.52');
insert into car (make, model, price) values ('Mercury', 'Mystique', '64143.57');
insert into car (make, model, price) values ('Mazda', 'Millenia', '29517.61');
insert into car (make, model, price) values ('Cadillac', 'Catera', '77624.81');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '13414.85');
insert into car (make, model, price) values ('Maybach', '62', '74842.07');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '98444.88');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '63407.75');
insert into car (make, model, price) values ('Plymouth', 'Roadrunner', '40838.63');
insert into car (make, model, price) values ('Mazda', 'Protege', '84893.97');
insert into car (make, model, price) values ('Subaru', 'XT', '60109.60');
insert into car (make, model, price) values ('Lexus', 'GS', '90842.64');
insert into car (make, model, price) values ('Bentley', 'Continental', '50343.38');
insert into car (make, model, price) values ('Subaru', 'Alcyone SVX', '41103.60');
insert into car (make, model, price) values ('BMW', 'M5', '92123.32');
insert into car (make, model, price) values ('Chevrolet', 'APV', '97120.82');
insert into car (make, model, price) values ('Buick', 'Lucerne', '92225.20');
insert into car (make, model, price) values ('Suzuki', 'Swift', '23103.34');
insert into car (make, model, price) values ('Volvo', 'C70', '98214.58');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', '54263.16');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '52177.16');
insert into car (make, model, price) values ('Audi', 'A8', '53162.07');
insert into car (make, model, price) values ('Fillmore', 'Fillmore', '86798.66');
insert into car (make, model, price) values ('Lexus', 'SC', '88506.53');
insert into car (make, model, price) values ('Honda', 'Element', '56550.14');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '11111.48');
insert into car (make, model, price) values ('Toyota', 'Highlander', '77221.03');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '38311.70');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '72429.06');
insert into car (make, model, price) values ('Toyota', 'Solara', '79238.08');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '79273.23');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '67174.91');
insert into car (make, model, price) values ('Ford', 'Tempo', '30542.03');
insert into car (make, model, price) values ('Buick', 'LaCrosse', '11259.51');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '69219.16');
insert into car (make, model, price) values ('Dodge', 'Caravan', '27902.31');
insert into car (make, model, price) values ('MINI', 'Cooper', '53186.04');
insert into car (make, model, price) values ('Nissan', 'Versa', '57731.59');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '42863.31');
insert into car (make, model, price) values ('Kia', 'Spectra5', '69413.84');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '54104.14');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '10678.21');
insert into car (make, model, price) values ('Cadillac', 'Escalade ESV', '89801.92');
insert into car (make, model, price) values ('Saab', '9-4X', '49293.35');
insert into car (make, model, price) values ('Chevrolet', 'Equinox', '79203.62');
insert into car (make, model, price) values ('Ford', 'Taurus', '44915.25');
insert into car (make, model, price) values ('Ford', 'Escape', '79204.87');
insert into car (make, model, price) values ('Ford', 'C-MAX Hybrid', '20007.40');
insert into car (make, model, price) values ('Infiniti', 'M', '30719.14');
insert into car (make, model, price) values ('Ford', 'Ranger', '60446.32');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '35089.20');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '10103.44');
insert into car (make, model, price) values ('Tesla', 'Roadster', '89177.27');
insert into car (make, model, price) values ('Ford', 'Probe', '54689.24');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '99969.77');
insert into car (make, model, price) values ('Mercury', 'Topaz', '77959.94');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '72840.84');
insert into car (make, model, price) values ('BMW', '7 Series', '76185.48');
insert into car (make, model, price) values ('Buick', 'LeSabre', '89709.82');
insert into car (make, model, price) values ('Nissan', '350Z', '70990.21');
insert into car (make, model, price) values ('Isuzu', 'Amigo', '19552.44');
insert into car (make, model, price) values ('Mazda', 'B-Series', '89285.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '51486.77');
insert into car (make, model, price) values ('Ford', 'Mustang', '74475.52');
insert into car (make, model, price) values ('Ford', 'F350', '97111.00');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '40887.54');
insert into car (make, model, price) values ('Ferrari', 'F430', '49536.43');
insert into car (make, model, price) values ('Ford', 'Mustang', '63684.74');
insert into car (make, model, price) values ('Mazda', 'MX-5', '94836.93');
insert into car (make, model, price) values ('Audi', 'S8', '99410.54');
insert into car (make, model, price) values ('BMW', '6 Series', '20616.70');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '85067.38');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '71632.35');
insert into car (make, model, price) values ('Audi', 'A8', '60365.65');
insert into car (make, model, price) values ('Chrysler', '300', '24612.49');
insert into car (make, model, price) values ('Buick', 'Hearse', '98808.04');
insert into car (make, model, price) values ('Mercury', 'Mariner', '23990.50');
insert into car (make, model, price) values ('Volvo', 'S80', '80777.17');
insert into car (make, model, price) values ('Dodge', 'Challenger', '11321.58');
insert into car (make, model, price) values ('Dodge', 'Charger', '26112.82');
insert into car (make, model, price) values ('Ford', 'Taurus X', '58236.19');
insert into car (make, model, price) values ('Saab', '900', '11736.22');
insert into car (make, model, price) values ('Ford', 'Lightning', '85722.59');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '45563.08');
insert into car (make, model, price) values ('Pontiac', 'Daewoo Kalos', '50591.45');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '38827.25');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '25683.35');
insert into car (make, model, price) values ('Toyota', 'Xtra', '57560.87');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '23572.49');
insert into car (make, model, price) values ('Mazda', 'B2500', '28380.81');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '87565.62');
insert into car (make, model, price) values ('Lexus', 'ES', '59060.72');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '26673.63');
insert into car (make, model, price) values ('Lotus', 'Elise', '29251.01');
insert into car (make, model, price) values ('Kia', 'Soul', '24205.14');
insert into car (make, model, price) values ('Mazda', '929', '62563.58');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '33377.24');
insert into car (make, model, price) values ('Cadillac', 'CTS', '20000.95');
insert into car (make, model, price) values ('Volkswagen', 'rio', '69176.74');
insert into car (make, model, price) values ('Lexus', 'IS', '86182.03');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '82606.36');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter 3500', '83418.50');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '80954.80');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '75645.51');
insert into car (make, model, price) values ('Volvo', 'S80', '20076.95');
insert into car (make, model, price) values ('Volvo', 'C70', '98618.94');
insert into car (make, model, price) values ('Infiniti', 'I', '86220.42');
insert into car (make, model, price) values ('Honda', 'CR-X', '94432.63');
insert into car (make, model, price) values ('Audi', 'S4', '85568.57');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '13383.35');
insert into car (make, model, price) values ('Lexus', 'SC', '35232.39');
insert into car (make, model, price) values ('Mazda', 'B2600', '43407.31');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '16787.78');
insert into car (make, model, price) values ('GMC', 'Sierra', '74190.58');
insert into car (make, model, price) values ('Infiniti', 'QX', '25888.80');
insert into car (make, model, price) values ('Buick', 'Riviera', '41921.80');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '62894.65');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '62560.03');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '96362.33');
insert into car (make, model, price) values ('Ford', 'Edge', '70893.22');
insert into car (make, model, price) values ('Ford', 'Windstar', '67996.71');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '50749.42');
insert into car (make, model, price) values ('Plymouth', 'Volare', '26629.94');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '42694.99');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '90811.39');
insert into car (make, model, price) values ('Mercury', 'Capri', '38275.43');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '53703.59');
insert into car (make, model, price) values ('Cadillac', 'SRX', '35674.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '27925.14');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '99101.62');
insert into car (make, model, price) values ('Daewoo', 'Nubira', '76473.18');
insert into car (make, model, price) values ('Dodge', 'Colt', '99788.74');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '92622.06');
insert into car (make, model, price) values ('Infiniti', 'Q', '70618.25');
insert into car (make, model, price) values ('Kia', 'Rio', '36203.27');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '17249.27');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '26473.58');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '47843.91');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '18696.54');
insert into car (make, model, price) values ('GMC', 'Envoy', '67619.71');
insert into car (make, model, price) values ('Maserati', 'Karif', '35428.18');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '65221.89');
insert into car (make, model, price) values ('Saturn', 'VUE', '36360.07');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '53649.94');
insert into car (make, model, price) values ('Suzuki', 'Reno', '57109.07');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '66802.37');
insert into car (make, model, price) values ('Ford', 'Edge', '33750.86');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '52405.39');
insert into car (make, model, price) values ('Suzuki', 'Swift', '88601.22');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '94659.40');
insert into car (make, model, price) values ('Nissan', 'Titan', '71563.65');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '75833.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '38744.36');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '28219.11');
insert into car (make, model, price) values ('Lamborghini', 'Reventón', '65995.83');
insert into car (make, model, price) values ('Chevrolet', 'Express', '59388.57');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '20822.76');
insert into car (make, model, price) values ('Chrysler', '200', '67345.97');
insert into car (make, model, price) values ('Nissan', 'Xterra', '55991.84');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '58482.26');
insert into car (make, model, price) values ('Dodge', 'Caravan', '95467.02');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '53783.52');
insert into car (make, model, price) values ('Infiniti', 'I', '87435.86');
insert into car (make, model, price) values ('Dodge', 'Avenger', '29803.30');
insert into car (make, model, price) values ('Chrysler', 'Pacifica', '48644.96');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '27269.01');
insert into car (make, model, price) values ('Toyota', 'Prius', '18987.87');
insert into car (make, model, price) values ('Pontiac', 'Montana SV6', '75446.67');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '59627.42');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '19600.06');
insert into car (make, model, price) values ('Porsche', 'Cayman', '32628.94');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '31570.16');
insert into car (make, model, price) values ('Nissan', 'Sentra', '65127.11');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '83199.21');
insert into car (make, model, price) values ('Toyota', 'Solara', '37754.29');
insert into car (make, model, price) values ('Chrysler', 'LHS', '98076.35');
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', '32727.34');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '68063.11');
insert into car (make, model, price) values ('Chevrolet', '3500', '45474.61');
insert into car (make, model, price) values ('Nissan', 'Maxima', '83828.96');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter', '65643.87');
insert into car (make, model, price) values ('Ford', 'E150', '78106.21');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '28787.09');
insert into car (make, model, price) values ('Mercedes-Benz', '190E', '18838.68');
insert into car (make, model, price) values ('Land Rover', 'LR2', '69482.15');
insert into car (make, model, price) values ('Buick', 'Rainier', '81428.92');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '92319.28');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '76199.47');
insert into car (make, model, price) values ('BMW', 'X5 M', '37196.71');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '42936.32');
insert into car (make, model, price) values ('GMC', 'Canyon', '48858.08');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '85733.69');
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', '79326.64');
insert into car (make, model, price) values ('Honda', 'CR-X', '32061.46');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '97907.37');
insert into car (make, model, price) values ('Nissan', 'Quest', '32607.42');
insert into car (make, model, price) values ('GMC', 'Suburban 2500', '10129.03');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '48429.15');
insert into car (make, model, price) values ('Audi', 'S6', '22354.91');
insert into car (make, model, price) values ('Saab', '9-2X', '73449.58');
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', '93544.76');
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', '91808.47');
insert into car (make, model, price) values ('Plymouth', 'Laser', '40131.37');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '96282.24');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '25865.48');
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', '71828.61');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', '98156.58');
insert into car (make, model, price) values ('Scion', 'xD', '16963.18');
insert into car (make, model, price) values ('Volkswagen', 'rio', '14770.52');
insert into car (make, model, price) values ('Nissan', 'Quest', '82964.18');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '54202.96');
insert into car (make, model, price) values ('Isuzu', 'Hombre', '99563.02');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '84127.03');
insert into car (make, model, price) values ('Mitsubishi', 'Cordia', '30904.88');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '12143.52');
insert into car (make, model, price) values ('Infiniti', 'Q', '73839.46');
insert into car (make, model, price) values ('BMW', '325', '84705.87');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '97094.81');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '65344.48');
insert into car (make, model, price) values ('Ford', 'Taurus', '24241.44');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '47595.74');
insert into car (make, model, price) values ('Volvo', 'V50', '25054.67');
insert into car (make, model, price) values ('Chrysler', 'LHS', '76055.97');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '12448.59');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '99186.78');
insert into car (make, model, price) values ('Plymouth', 'Laser', '16347.51');
insert into car (make, model, price) values ('Toyota', 'Solara', '43264.61');
insert into car (make, model, price) values ('Audi', '5000S', '11674.01');
insert into car (make, model, price) values ('Ford', 'Explorer', '31506.57');
insert into car (make, model, price) values ('Mercedes-Benz', 'GLK-Class', '81734.21');
insert into car (make, model, price) values ('BMW', 'X6', '49589.08');
insert into car (make, model, price) values ('Plymouth', 'Roadrunner', '28925.75');
insert into car (make, model, price) values ('Isuzu', 'Hombre', '65278.60');
insert into car (make, model, price) values ('Maybach', '57', '26702.34');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '91085.89');
insert into car (make, model, price) values ('Nissan', 'Frontier', '68639.27');
insert into car (make, model, price) values ('Honda', 'Odyssey', '38949.25');
insert into car (make, model, price) values ('Toyota', '4Runner', '18991.42');
insert into car (make, model, price) values ('Infiniti', 'QX', '91275.58');
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', '31013.00');
insert into car (make, model, price) values ('Nissan', 'NV3500', '52647.39');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '25669.07');
insert into car (make, model, price) values ('Honda', 'Civic', '25197.73');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '39283.94');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '93601.87');
insert into car (make, model, price) values ('Cadillac', 'CTS', '43875.57');
insert into car (make, model, price) values ('Infiniti', 'G', '39410.27');
insert into car (make, model, price) values ('Acura', 'RDX', '97868.85');
insert into car (make, model, price) values ('Ford', 'Focus', '49035.89');
insert into car (make, model, price) values ('Ford', 'Courier', '51346.46');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '90835.82');
insert into car (make, model, price) values ('Volvo', 'C70', '78231.17');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '34158.19');
insert into car (make, model, price) values ('Mercedes-Benz', '300SE', '69854.90');
insert into car (make, model, price) values ('Porsche', '944', '79861.12');
insert into car (make, model, price) values ('Nissan', '370Z', '10341.43');
insert into car (make, model, price) values ('Buick', 'Skylark', '70126.76');
insert into car (make, model, price) values ('Foose', 'Hemisfear', '93816.23');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '67687.21');
insert into car (make, model, price) values ('Nissan', 'Rogue', '32312.59');
insert into car (make, model, price) values ('Ford', 'F450', '18375.84');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '36624.23');
insert into car (make, model, price) values ('Volkswagen', 'Routan', '60717.31');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '34546.63');
insert into car (make, model, price) values ('Pontiac', 'GTO', '84022.86');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '59857.11');
insert into car (make, model, price) values ('Suzuki', 'Sidekick', '41797.15');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '60574.00');
insert into car (make, model, price) values ('Subaru', 'Legacy', '16425.64');
insert into car (make, model, price) values ('Honda', 'Passport', '98091.98');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '75577.22');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '69186.48');
insert into car (make, model, price) values ('Dodge', 'Caravan', '40967.23');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '48435.71');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '67091.72');
insert into car (make, model, price) values ('Mercury', 'Tracer', '87134.78');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '93065.77');
insert into car (make, model, price) values ('Toyota', 'Camry', '30766.12');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '14795.07');
insert into car (make, model, price) values ('Volvo', 'C70', '94337.60');
insert into car (make, model, price) values ('Mercury', 'Villager', '49179.80');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '97795.86');
insert into car (make, model, price) values ('Ford', 'Expedition', '78601.75');
insert into car (make, model, price) values ('Pontiac', 'Montana', '32851.79');
insert into car (make, model, price) values ('Honda', 'CR-X', '46773.90');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '97401.31');
insert into car (make, model, price) values ('Volvo', 'S70', '60092.24');
insert into car (make, model, price) values ('BMW', 'Z3', '59271.68');
insert into car (make, model, price) values ('Toyota', 'Corolla', '32918.79');
insert into car (make, model, price) values ('Chrysler', 'LeBaron', '72550.96');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '39644.41');
insert into car (make, model, price) values ('Chevrolet', 'Colorado', '33842.33');
insert into car (make, model, price) values ('Dodge', 'Caliber', '52144.14');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '75455.31');
insert into car (make, model, price) values ('Bentley', 'Arnage', '79841.15');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', '26627.35');
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', '78891.29');
insert into car (make, model, price) values ('Saab', '9000', '87111.24');
insert into car (make, model, price) values ('Hyundai', 'XG350', '97440.80');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '89591.89');
insert into car (make, model, price) values ('Acura', 'RDX', '54149.03');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '53816.38');
insert into car (make, model, price) values ('Nissan', 'Frontier', '28130.39');
insert into car (make, model, price) values ('Buick', 'Century', '77035.24');
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', '10420.04');
insert into car (make, model, price) values ('Lexus', 'LX', '91104.68');
insert into car (make, model, price) values ('Ford', 'Escort', '41873.46');
insert into car (make, model, price) values ('Honda', 'Accord', '33252.64');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '60955.23');
insert into car (make, model, price) values ('Buick', 'Skyhawk', '45852.71');
insert into car (make, model, price) values ('Isuzu', 'Hombre', '80601.66');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '33232.22');
insert into car (make, model, price) values ('Ford', 'F250', '10201.69');
insert into car (make, model, price) values ('Ford', 'Windstar', '90408.98');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '71115.74');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '55932.66');
insert into car (make, model, price) values ('Morgan', 'Aero 8', '72130.07');
insert into car (make, model, price) values ('Saab', '9000', '26188.58');
insert into car (make, model, price) values ('MINI', 'Clubman', '51555.63');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '30694.80');
insert into car (make, model, price) values ('Jeep', 'Liberty', '65372.46');
insert into car (make, model, price) values ('Acura', 'RDX', '84705.31');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '37859.86');
insert into car (make, model, price) values ('Buick', 'Terraza', '87508.20');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '63605.92');
insert into car (make, model, price) values ('Nissan', 'GT-R', '96566.81');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '59146.37');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '22194.42');
insert into car (make, model, price) values ('Audi', 'Q5', '26085.37');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '22080.12');
insert into car (make, model, price) values ('MINI', 'Cooper', '49155.18');
insert into car (make, model, price) values ('Eagle', 'Talon', '56903.87');
insert into car (make, model, price) values ('Acura', 'RL', '53384.59');
insert into car (make, model, price) values ('Nissan', 'Altima', '16058.83');
insert into car (make, model, price) values ('Mitsubishi', 'Starion', '54171.06');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '30257.13');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '14860.63');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '64974.79');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '96035.93');
insert into car (make, model, price) values ('GMC', 'Vandura 1500', '21074.88');
insert into car (make, model, price) values ('Land Rover', 'LR3', '29923.83');
insert into car (make, model, price) values ('Porsche', '968', '35152.08');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '51880.07');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '45767.48');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '82336.93');
insert into car (make, model, price) values ('Mitsubishi', 'L300', '94741.68');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '47105.73');
insert into car (make, model, price) values ('Suzuki', 'Equator', '44047.15');
insert into car (make, model, price) values ('GMC', 'Jimmy', '86879.74');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', '96379.51');
insert into car (make, model, price) values ('Mazda', 'RX-7', '10838.48');
insert into car (make, model, price) values ('Ford', 'Mustang', '51319.45');
insert into car (make, model, price) values ('GMC', 'Suburban 2500', '10407.38');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '38647.37');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '35950.87');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '74996.88');
insert into car (make, model, price) values ('Isuzu', 'Hombre', '34377.64');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '72034.86');
insert into car (make, model, price) values ('Nissan', '200SX', '46896.58');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '42326.58');
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage S', '11139.83');
insert into car (make, model, price) values ('Kia', 'Rio', '14009.79');
insert into car (make, model, price) values ('Geo', 'Metro', '41498.74');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '78812.07');
insert into car (make, model, price) values ('Chevrolet', 'Malibu', '17602.77');
insert into car (make, model, price) values ('Porsche', 'Cayman', '73105.22');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '39820.28');
insert into car (make, model, price) values ('Dodge', 'Stratus', '64829.18');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B150', '33855.65');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '88778.94');
insert into car (make, model, price) values ('BMW', 'Z3', '19136.89');
insert into car (make, model, price) values ('Honda', 'Accord', '68743.87');
insert into car (make, model, price) values ('BMW', '330', '62156.53');
insert into car (make, model, price) values ('Suzuki', 'Swift', '13345.90');
insert into car (make, model, price) values ('Audi', 'Quattro', '17393.37');
insert into car (make, model, price) values ('BMW', '7 Series', '31309.21');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '52230.79');
insert into car (make, model, price) values ('Pontiac', 'Gemini', '41364.00');
insert into car (make, model, price) values ('Infiniti', 'M', '35890.10');
insert into car (make, model, price) values ('Lotus', 'Esprit', '23672.30');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '32601.40');
insert into car (make, model, price) values ('Mercury', 'Cougar', '38120.44');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '31849.73');
insert into car (make, model, price) values ('Pontiac', 'G6', '11662.52');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '54018.35');
insert into car (make, model, price) values ('Acura', 'Vigor', '12784.11');
insert into car (make, model, price) values ('Ford', 'Mustang', '71431.20');
insert into car (make, model, price) values ('BMW', 'M3', '28068.57');
insert into car (make, model, price) values ('Saturn', 'S-Series', '14980.93');
insert into car (make, model, price) values ('Kia', 'Spectra', '58762.06');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '70950.90');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '51998.79');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G30', '49542.78');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '43676.91');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '16144.44');
insert into car (make, model, price) values ('Subaru', 'Forester', '56375.81');
insert into car (make, model, price) values ('Dodge', 'Caravan', '43213.60');
insert into car (make, model, price) values ('Honda', 'Civic', '23621.85');
insert into car (make, model, price) values ('Nissan', '300ZX', '87062.68');
insert into car (make, model, price) values ('Mercury', 'Sable', '46608.51');
insert into car (make, model, price) values ('Lexus', 'ES', '59428.66');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '31933.47');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '68577.13');
insert into car (make, model, price) values ('Hummer', 'H3', '66484.05');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '63786.48');
insert into car (make, model, price) values ('Toyota', 'T100', '91394.91');
insert into car (make, model, price) values ('Acura', 'TL', '47707.78');
insert into car (make, model, price) values ('Mazda', 'Mazda3', '83527.57');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '14968.45');
insert into car (make, model, price) values ('Bentley', 'Brooklands', '72269.07');
insert into car (make, model, price) values ('Ford', 'Flex', '86444.89');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '54887.93');
insert into car (make, model, price) values ('Lexus', 'IS', '86805.55');
insert into car (make, model, price) values ('Nissan', '300ZX', '68860.52');
insert into car (make, model, price) values ('Jeep', 'Liberty', '71713.84');
insert into car (make, model, price) values ('BMW', '3 Series', '52833.86');
insert into car (make, model, price) values ('Buick', 'Skylark', '71889.40');
insert into car (make, model, price) values ('Mazda', 'CX-7', '84420.45');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '29465.09');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '75853.07');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '73504.27');
insert into car (make, model, price) values ('Audi', 'S4', '28196.76');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '30330.16');
insert into car (make, model, price) values ('Cadillac', 'DTS', '88577.43');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '90094.54');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '80531.86');
insert into car (make, model, price) values ('Cadillac', 'CTS', '92049.44');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '52467.13');
insert into car (make, model, price) values ('Ford', 'Bronco', '49692.63');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '23758.31');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '28333.31');
insert into car (make, model, price) values ('GMC', 'Savana', '63251.53');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '43760.68');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '99146.86');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '23256.67');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '94897.09');
insert into car (make, model, price) values ('Volkswagen', 'GLI', '12474.78');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '51329.88');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '97491.23');
insert into car (make, model, price) values ('Toyota', 'Supra', '57770.04');
insert into car (make, model, price) values ('Chevrolet', 'Traverse', '71415.34');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '49973.47');
insert into car (make, model, price) values ('Cadillac', 'CTS', '70195.29');
insert into car (make, model, price) values ('Chevrolet', 'Traverse', '42762.52');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '25658.71');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '11465.32');
insert into car (make, model, price) values ('Acura', 'NSX', '60818.54');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '54049.76');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '70061.14');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '73944.79');
insert into car (make, model, price) values ('GMC', 'Sierra', '18683.58');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '56938.47');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '60130.42');
insert into car (make, model, price) values ('Maserati', 'Gran Sport', '97066.16');
insert into car (make, model, price) values ('Dodge', 'Caliber', '20612.27');
insert into car (make, model, price) values ('Kia', 'Sephia', '16550.37');
insert into car (make, model, price) values ('Chrysler', '300', '17708.64');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '22630.19');
insert into car (make, model, price) values ('Toyota', 'MR2', '56892.94');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '90813.15');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '35883.81');
insert into car (make, model, price) values ('Subaru', 'Baja', '48323.92');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '83603.57');
insert into car (make, model, price) values ('Pontiac', 'LeMans', '36953.11');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B350', '73980.89');
insert into car (make, model, price) values ('Nissan', 'Quest', '30826.40');
insert into car (make, model, price) values ('Audi', 'RS6', '92418.62');
insert into car (make, model, price) values ('Ford', 'Thunderbird', '48365.35');
insert into car (make, model, price) values ('Cadillac', 'SRX', '85049.85');
insert into car (make, model, price) values ('Chrysler', 'Concorde', '59975.23');
insert into car (make, model, price) values ('GMC', 'Sonoma', '63095.47');
insert into car (make, model, price) values ('Lotus', 'Esprit', '37645.90');
insert into car (make, model, price) values ('Saab', '9-5', '20412.97');
insert into car (make, model, price) values ('Honda', 'CR-V', '66860.25');
insert into car (make, model, price) values ('Ford', 'Fusion', '34256.68');
insert into car (make, model, price) values ('Honda', 'Accord', '10192.54');
insert into car (make, model, price) values ('Volkswagen', 'Phaeton', '46485.15');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '37681.16');
insert into car (make, model, price) values ('Audi', 'A8', '62585.68');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '54779.12');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '10959.27');
insert into car (make, model, price) values ('Mazda', 'Navajo', '59098.90');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '80303.38');
insert into car (make, model, price) values ('Ford', 'Windstar', '87126.93');
insert into car (make, model, price) values ('Nissan', 'Altima', '23990.54');
insert into car (make, model, price) values ('Subaru', 'XT', '30053.37');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '30575.81');
insert into car (make, model, price) values ('Dodge', 'D250 Club', '46704.68');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '51222.73');
insert into car (make, model, price) values ('Ford', 'Explorer', '41397.86');
insert into car (make, model, price) values ('Mercury', 'Sable', '14609.28');
insert into car (make, model, price) values ('Ford', 'F350', '26277.57');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '50203.40');
insert into car (make, model, price) values ('Subaru', 'Forester', '28911.03');
insert into car (make, model, price) values ('Volkswagen', 'rio', '31281.50');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '69192.75');
insert into car (make, model, price) values ('Chevrolet', 'Caprice', '64732.63');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '21647.35');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '90970.16');
insert into car (make, model, price) values ('GMC', 'Canyon', '94712.07');
insert into car (make, model, price) values ('Ford', 'Laser', '21436.02');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '22630.08');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '54547.31');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '71378.83');
insert into car (make, model, price) values ('Ford', 'Taurus', '31742.75');
insert into car (make, model, price) values ('GMC', 'Vandura 2500', '82848.28');
insert into car (make, model, price) values ('Plymouth', 'Colt', '50152.81');
insert into car (make, model, price) values ('Audi', '100', '62230.60');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '29274.93');
insert into car (make, model, price) values ('Lexus', 'GS', '35274.05');
insert into car (make, model, price) values ('Toyota', 'Camry', '96675.94');
insert into car (make, model, price) values ('Mercury', 'Sable', '20450.40');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '94695.81');
insert into car (make, model, price) values ('Ford', 'Windstar', '45622.92');
insert into car (make, model, price) values ('Kia', 'Sportage', '31188.00');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '82073.84');
insert into car (make, model, price) values ('Toyota', 'MR2', '55171.46');
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', '74674.89');
insert into car (make, model, price) values ('Honda', 'S2000', '27653.63');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '81912.08');
insert into car (make, model, price) values ('Nissan', '240SX', '41137.59');
insert into car (make, model, price) values ('Honda', 'CR-V', '30204.04');
insert into car (make, model, price) values ('Lexus', 'SC', '78589.80');
insert into car (make, model, price) values ('Infiniti', 'QX56', '95013.51');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '38219.35');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '65993.78');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '11429.45');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '60741.47');
insert into car (make, model, price) values ('MINI', 'Cooper', '58449.52');
insert into car (make, model, price) values ('BMW', '530', '62171.81');
insert into car (make, model, price) values ('Volvo', 'C70', '32330.48');
insert into car (make, model, price) values ('Oldsmobile', '88', '31386.23');
insert into car (make, model, price) values ('Honda', 'Pilot', '97868.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '51391.62');
insert into car (make, model, price) values ('Toyota', 'MR2', '38415.44');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '12580.40');
insert into car (make, model, price) values ('Chevrolet', '3500', '20174.56');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '60535.58');
insert into car (make, model, price) values ('Dodge', 'Avenger', '40833.47');
insert into car (make, model, price) values ('Dodge', 'Stratus', '32150.15');
insert into car (make, model, price) values ('Audi', 'S4', '85250.54');
insert into car (make, model, price) values ('Audi', 'S4', '29426.14');
insert into car (make, model, price) values ('Plymouth', 'Laser', '78711.02');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '83118.27');
insert into car (make, model, price) values ('Porsche', '944', '79486.33');
insert into car (make, model, price) values ('Ford', 'F350', '49500.53');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '81620.72');
insert into car (make, model, price) values ('Pontiac', 'Aztek', '69839.95');
insert into car (make, model, price) values ('Ford', 'Bronco', '52397.24');
insert into car (make, model, price) values ('Bentley', 'Azure T', '15480.90');
insert into car (make, model, price) values ('Oldsmobile', 'Alero', '46182.79');
insert into car (make, model, price) values ('Toyota', 'Matrix', '81155.08');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '78569.47');
insert into car (make, model, price) values ('Chevrolet', 'Beretta', '23221.67');
insert into car (make, model, price) values ('Honda', 'Prelude', '78385.60');
insert into car (make, model, price) values ('Chevrolet', '2500', '20701.47');
insert into car (make, model, price) values ('Kia', 'Forte', '64396.12');
insert into car (make, model, price) values ('Nissan', 'Maxima', '40445.71');
insert into car (make, model, price) values ('Mazda', 'B2000', '56952.51');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '60510.26');
insert into car (make, model, price) values ('Ford', 'Mustang', '11019.98');
insert into car (make, model, price) values ('Bentley', 'Continental Super', '20533.77');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '30635.57');
insert into car (make, model, price) values ('Lexus', 'ES', '62698.21');
insert into car (make, model, price) values ('Nissan', '240SX', '71730.01');
insert into car (make, model, price) values ('Subaru', 'Legacy', '27460.40');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '93288.63');
insert into car (make, model, price) values ('BMW', '7 Series', '83677.11');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '98546.58');
insert into car (make, model, price) values ('BMW', 'M5', '22426.60');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '93095.48');
insert into car (make, model, price) values ('Ford', 'F450', '79463.95');
insert into car (make, model, price) values ('Kia', 'Sorento', '23778.48');
insert into car (make, model, price) values ('Aston Martin', 'DB9', '66376.24');
insert into car (make, model, price) values ('Infiniti', 'JX', '63562.83');
insert into car (make, model, price) values ('Nissan', 'Sentra', '65644.02');
insert into car (make, model, price) values ('Aston Martin', 'Rapide', '29515.98');
insert into car (make, model, price) values ('Ford', 'Fusion', '48748.15');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '95000.23');
insert into car (make, model, price) values ('Ford', 'Bronco', '92844.69');
insert into car (make, model, price) values ('Dodge', 'Durango', '30387.41');
insert into car (make, model, price) values ('Infiniti', 'FX', '57335.01');
insert into car (make, model, price) values ('Toyota', 'Corolla', '69668.22');
insert into car (make, model, price) values ('Hummer', 'H1', '45403.23');
insert into car (make, model, price) values ('Dodge', 'Ram', '91513.03');
insert into car (make, model, price) values ('Bentley', 'Continental', '40679.67');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '86149.30');
insert into car (make, model, price) values ('Nissan', 'Titan', '47305.74');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '51106.75');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '70520.90');
insert into car (make, model, price) values ('Hyundai', 'Accent', '50592.91');
insert into car (make, model, price) values ('Eagle', 'Talon', '78315.80');
insert into car (make, model, price) values ('Mazda', 'Millenia', '66717.13');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '68693.80');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '79716.80');
insert into car (make, model, price) values ('Land Rover', 'LR4', '28479.84');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '34758.78');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '36205.72');
insert into car (make, model, price) values ('Volvo', 'XC70', '41848.61');
insert into car (make, model, price) values ('Land Rover', 'Defender 90', '64608.49');
insert into car (make, model, price) values ('Cadillac', 'Seville', '21756.32');
insert into car (make, model, price) values ('Bentley', 'Continental GT', '40912.77');
insert into car (make, model, price) values ('Buick', 'Regal', '93400.10');
insert into car (make, model, price) values ('Oldsmobile', '98', '52011.17');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '76888.48');
insert into car (make, model, price) values ('Honda', 'del Sol', '20352.21');
insert into car (make, model, price) values ('Saturn', 'L-Series', '15169.68');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', '33689.97');
insert into car (make, model, price) values ('Lincoln', 'Mark LT', '76157.53');
insert into car (make, model, price) values ('Audi', '90', '26203.70');
insert into car (make, model, price) values ('Infiniti', 'I', '51314.54');
insert into car (make, model, price) values ('Mercury', 'Cougar', '93263.43');
insert into car (make, model, price) values ('Mercedes-Benz', '300D', '26634.24');
insert into car (make, model, price) values ('Pontiac', 'Solstice', '23206.04');
insert into car (make, model, price) values ('Chrysler', 'LeBaron', '80069.40');
insert into car (make, model, price) values ('Dodge', 'Caliber', '87643.33');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '69346.03');
insert into car (make, model, price) values ('Saab', '900', '35976.04');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '15551.34');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '40922.36');
insert into car (make, model, price) values ('Pontiac', 'Monterey', '12499.95');
insert into car (make, model, price) values ('Volvo', 'C30', '56530.06');
insert into car (make, model, price) values ('Buick', 'Skylark', '33399.16');
insert into car (make, model, price) values ('Ford', 'E-Series', '21293.36');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '29711.12');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '46158.65');
insert into car (make, model, price) values ('Toyota', 'Prius', '60164.14');
insert into car (make, model, price) values ('GMC', 'Sierra', '79488.26');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '40763.70');
insert into car (make, model, price) values ('Mazda', 'B-Series', '38591.53');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '57381.05');
insert into car (make, model, price) values ('Buick', 'Century', '67632.08');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '95528.37');
insert into car (make, model, price) values ('GMC', '3500', '11769.81');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '37754.17');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '42043.00');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter 3500', '42412.36');
insert into car (make, model, price) values ('Ford', 'E150', '77662.56');
insert into car (make, model, price) values ('Lexus', 'GS', '53834.85');
insert into car (make, model, price) values ('Ford', 'Mustang', '79378.41');
insert into car (make, model, price) values ('Subaru', 'XT', '13373.57');
insert into car (make, model, price) values ('Buick', 'Roadmaster', '89558.68');
insert into car (make, model, price) values ('Mazda', 'B-Series', '89944.31');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '91185.92');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '17621.90');
insert into car (make, model, price) values ('Toyota', '4Runner', '12801.43');
insert into car (make, model, price) values ('Volvo', 'V70', '77589.14');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '64291.18');
insert into car (make, model, price) values ('Lamborghini', 'Reventón', '13501.64');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '43385.33');
insert into car (make, model, price) values ('Buick', 'Coachbuilder', '88745.42');
insert into car (make, model, price) values ('Kia', 'Amanti', '77774.58');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '37890.62');
insert into car (make, model, price) values ('Buick', 'Coachbuilder', '58358.42');
insert into car (make, model, price) values ('Suzuki', 'Samurai', '81421.00');
insert into car (make, model, price) values ('BMW', 'X3', '38635.34');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '24227.02');
insert into car (make, model, price) values ('BMW', 'X6', '80919.28');
insert into car (make, model, price) values ('Buick', 'Somerset', '42618.30');
insert into car (make, model, price) values ('Dodge', 'Charger', '48800.87');
insert into car (make, model, price) values ('Mitsubishi', 'Precis', '92257.98');
insert into car (make, model, price) values ('Lexus', 'GS', '90563.55');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '83992.88');
insert into car (make, model, price) values ('Hyundai', 'Excel', '20097.17');
insert into car (make, model, price) values ('Ford', 'Bronco II', '46373.13');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '28027.65');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 1500', '34219.96');
insert into car (make, model, price) values ('Mitsubishi', 'GTO', '10821.45');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '14063.71');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '37767.17');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '66294.80');
insert into car (make, model, price) values ('GMC', 'Jimmy', '40640.77');
insert into car (make, model, price) values ('Saab', '9000', '79149.19');
insert into car (make, model, price) values ('Suzuki', 'Verona', '80182.50');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '33895.60');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '78865.35');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '52691.28');
insert into car (make, model, price) values ('Subaru', 'SVX', '56686.21');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '40820.01');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '51624.73');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '68140.94');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '69385.42');
insert into car (make, model, price) values ('BMW', '5 Series', '91212.36');
insert into car (make, model, price) values ('Dodge', 'Durango', '14235.69');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '86967.83');
insert into car (make, model, price) values ('Chrysler', '300C', '61205.44');
insert into car (make, model, price) values ('Cadillac', 'Eldorado', '90229.87');
insert into car (make, model, price) values ('Ford', 'Explorer', '78106.19');
insert into car (make, model, price) values ('Honda', 'del Sol', '58675.34');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '23515.44');
insert into car (make, model, price) values ('Nissan', 'GT-R', '57337.51');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '98467.13');
insert into car (make, model, price) values ('Lexus', 'GX', '53231.76');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '79972.86');
insert into car (make, model, price) values ('Infiniti', 'G', '45656.52');
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', '45975.76');
insert into car (make, model, price) values ('Audi', 'S4', '91886.09');
insert into car (make, model, price) values ('Hyundai', 'Accent', '52927.03');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '12749.63');
insert into car (make, model, price) values ('Audi', 'TT', '39887.37');
insert into car (make, model, price) values ('BMW', '6 Series', '40215.69');
insert into car (make, model, price) values ('Toyota', 'Camry Hybrid', '74468.00');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '31736.13');
insert into car (make, model, price) values ('Hummer', 'H2', '15007.68');
insert into car (make, model, price) values ('Acura', 'RL', '55187.39');
insert into car (make, model, price) values ('Hyundai', 'Tucson', '65973.54');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '45997.39');
insert into car (make, model, price) values ('Toyota', 'Camry', '31231.14');
insert into car (make, model, price) values ('BMW', 'Z4 M', '64325.45');
insert into car (make, model, price) values ('Volvo', 'C30', '32164.60');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '36017.85');
insert into car (make, model, price) values ('Dodge', 'Colt', '17266.30');
insert into car (make, model, price) values ('Ferrari', 'F430', '17941.82');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '11144.58');
insert into car (make, model, price) values ('Toyota', 'Previa', '95781.28');
insert into car (make, model, price) values ('Acura', 'SLX', '16563.80');
insert into car (make, model, price) values ('Toyota', 'Camry', '59323.82');
insert into car (make, model, price) values ('Cadillac', 'Seville', '87786.40');
insert into car (make, model, price) values ('Pontiac', 'Torrent', '65517.90');
insert into car (make, model, price) values ('Mitsubishi', 'Starion', '81205.58');
insert into car (make, model, price) values ('Rolls-Royce', 'Phantom', '88925.67');
insert into car (make, model, price) values ('Hyundai', 'Genesis', '51102.54');
insert into car (make, model, price) values ('Ford', 'Focus', '96714.50');
insert into car (make, model, price) values ('Subaru', 'Leone', '29201.04');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '28871.92');
insert into car (make, model, price) values ('Suzuki', 'Aerio', '21143.78');
insert into car (make, model, price) values ('Audi', 'A8', '26241.86');
insert into car (make, model, price) values ('Ford', 'F250', '42729.11');
insert into car (make, model, price) values ('Mercury', 'Villager', '62111.65');
insert into car (make, model, price) values ('Dodge', 'Spirit', '79752.99');
insert into car (make, model, price) values ('Pontiac', '6000', '26275.72');
insert into car (make, model, price) values ('Toyota', 'Echo', '20796.45');
insert into car (make, model, price) values ('Suzuki', 'Swift', '74406.72');
insert into car (make, model, price) values ('Chevrolet', 'Express', '25548.61');
insert into car (make, model, price) values ('Mazda', 'CX-5', '26306.92');
insert into car (make, model, price) values ('Volvo', 'C70', '52508.52');
insert into car (make, model, price) values ('Ford', 'Ranger', '39498.53');
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', '79919.51');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '23812.47');
insert into car (make, model, price) values ('Jeep', 'Commander', '70554.95');
insert into car (make, model, price) values ('GMC', 'Canyon', '62497.30');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '90567.24');
insert into car (make, model, price) values ('Subaru', 'Forester', '71747.43');
insert into car (make, model, price) values ('Honda', 'Element', '96250.62');
insert into car (make, model, price) values ('Plymouth', 'Horizon', '99222.53');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '94160.09');
insert into car (make, model, price) values ('Eagle', 'Summit', '53105.56');
insert into car (make, model, price) values ('Jaguar', 'XK Series', '96771.10');
insert into car (make, model, price) values ('Ford', 'Mustang', '88378.12');
insert into car (make, model, price) values ('Infiniti', 'M', '57108.39');
insert into car (make, model, price) values ('Honda', 'Accord', '56610.06');
insert into car (make, model, price) values ('Chevrolet', 'Colorado', '44768.21');
insert into car (make, model, price) values ('MINI', 'Countryman', '62303.33');
insert into car (make, model, price) values ('Subaru', 'Forester', '57337.00');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '68541.31');
insert into car (make, model, price) values ('Toyota', 'RAV4', '87661.25');
insert into car (make, model, price) values ('Dodge', 'Stratus', '99121.61');
insert into car (make, model, price) values ('Lexus', 'SC', '31025.84');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '63681.30');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '94160.30');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '88460.24');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '26194.56');
insert into car (make, model, price) values ('Chrysler', 'Concorde', '10019.25');
insert into car (make, model, price) values ('Pontiac', 'GTO', '60568.87');
insert into car (make, model, price) values ('Mercedes-Benz', '400SE', '35057.05');
insert into car (make, model, price) values ('Mitsubishi', 'Diamante', '56542.77');
insert into car (make, model, price) values ('BMW', '525', '18941.64');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '32561.77');
insert into car (make, model, price) values ('GMC', 'Sonoma', '91864.72');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '50366.06');
insert into car (make, model, price) values ('Lexus', 'RX', '93477.76');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '64568.49');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '17354.80');
insert into car (make, model, price) values ('Dodge', 'Neon', '65472.16');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '44967.99');
insert into car (make, model, price) values ('Toyota', 'T100 Xtra', '93109.37');
insert into car (make, model, price) values ('Hyundai', 'Genesis Coupe', '53121.30');
insert into car (make, model, price) values ('Audi', 'A6', '59137.09');
insert into car (make, model, price) values ('BMW', 'M6', '18481.39');
insert into car (make, model, price) values ('Toyota', 'Prius', '84411.28');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '16529.90');
insert into car (make, model, price) values ('Jeep', 'Patriot', '25928.05');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '26207.26');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '89452.97');
insert into car (make, model, price) values ('Mercury', 'Sable', '74398.63');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '21324.60');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '79066.61');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '10090.68');
insert into car (make, model, price) values ('Ford', 'Explorer', '75364.78');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '71114.23');
insert into car (make, model, price) values ('BMW', '7 Series', '24080.16');
insert into car (make, model, price) values ('Mazda', '626', '26195.74');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '65429.73');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '11146.18');
insert into car (make, model, price) values ('Volvo', 'S90', '78870.63');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '18324.33');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', '16601.83');
insert into car (make, model, price) values ('Aptera', 'Typ-1', '10372.62');
insert into car (make, model, price) values ('Subaru', 'Alcyone SVX', '88099.28');
insert into car (make, model, price) values ('Chevrolet', 'Cobalt', '58327.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '71942.82');
insert into car (make, model, price) values ('Audi', 'Q7', '30873.68');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 2500', '36225.61');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '57780.72');
insert into car (make, model, price) values ('Toyota', 'Camry', '57581.57');
insert into car (make, model, price) values ('Subaru', 'Legacy', '43335.72');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '22857.71');
insert into car (make, model, price) values ('Subaru', 'Leone', '58468.30');
insert into car (make, model, price) values ('Volvo', 'XC90', '73658.53');
insert into car (make, model, price) values ('Lexus', 'SC', '91537.94');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '95685.53');
insert into car (make, model, price) values ('BMW', '6 Series', '28246.46');
